### ISSUE TITLE
[FEATURE REQUEST] HypeSquad Symbols on /profile

### ISSUE THREAD

**Issue by IAmAFrenchFry** [humboldt123/the-thunderhead#27]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
I’d like there to be a symbol on /profile for HypeSquaders. The symbol would be their house logo thing. It could be in the top left corner or smth.

**Describe alternatives you've considered**
Just text saying “HypeSquad” or something.

**Additional context**

**Comment by humboldt123** [comment]
This has been added to the bot in 83c2c816c7bc2248963182313102f40e2386c25e.
