### ISSUE TITLE
[FEATURE REQUEST] Automagical additions to market

### ISSUE THREAD

**Issue by IAmAFrenchFry** [humboldt123/the-thunderhead#28]
The market is empty or almost empty often, and there are not regular additions to it. It would be super cool if there was a way to, I don’t know, add items to a list and then have that list be randomly picked from maybe every 20 minutes and the item picked would be added to the market?

**Just a thought.** 

Additionally, it would be cool to have more types of items so that more people actually want to buy from the market, such as things that are expensive and allow you to do dailys and rob in 24 hours, but after a week their gone. Something like that, but that’s separate. Mostly the first thing.

**Comment by humboldt123** [comment]
I'm assigning you to it. We're using enmap instead of writing to a JSON file.

**Comment by humboldt123** [comment]
I say this because your old code for it won't work.

**Comment by humboldt123** [comment]
Nobody is doing this so I'm locking this issue.
