### ISSUE TITLE
polls but good

### ISSUE THREAD

**Issue by Microtransagolor** [humboldt123/the-thunderhead#38]
make polls have a time you can set so when they end you can see the results(embed edited to show how many check marks and xs and maybe a percent for each if that would be possible) and if possible making thunderhead delete a reaction if someone ries to vote for both

**Comment by humboldt123** [comment]
ｏｏｏｈ- That sounds like a great idea. I'll work on that now.

**Comment by humboldt123** [comment]
Alright so the plan is:

- [ ] Timed Polls
- [ ] Once over show stats
- [ ] Custom Options (More than just two)
- [ ] Block dual votes

**Comment by humboldt123** [comment]
Honestly some polls are going to be open so I won't block dual votes.

**Comment by humboldt123** [comment]
Whelp this is 50% done but I don't think its that important to finish the rest. If anybody knows JS and wants to; they can make a pr. Onto the next issue!
