### ISSUE TITLE
good ideas

### ISSUE THREAD

**Issue by Microtransagolor** [humboldt123/the-thunderhead#39]
here are some epic suggestions for you 
Make /play a search function like before, urls are tedious 
add pig latin as a language
make /suggest dm syou a suggestion instead of github link
remove /spoilers
add custom prefixes instead of just smelly /
add a fifth command page for fun commands
make thunderhead able to access rss feeds if it's not already
maake stuff more straightforward to figure out how to use commands, and view stock prices instead of sending lots of messages
maybe make help one message and you use up/down emojis to go through them

**Comment by humboldt123** [comment]
The content of the issues?

**Comment by Microtransagolor** [comment]
oopss

**Comment by humboldt123** [comment]
Please open a new one.

**Comment by Microtransagolor** [comment]
i'll edit this

**Comment by humboldt123** [comment]
Things to do

- [ ] Fix needing urls for `/play` (this is actually a bug)
- [ ]  Custom Prefixes
- [ ] make stuff more straightforward to figure out how to use commands, and view stock prices instead of sending lots of messages
- [ ] Emoji Scroll through stocks

**Comment by humboldt123** [comment]
Open more issues for the other stuff but I fixed the play command error. It wasnt my code it was an issue with the package version I was using :/

**Comment by Microtransagolor** [comment]
you better add pig latin as a language

**Comment by humboldt123** [comment]
Pig Latin does not have a flag.

**Comment by Microtransagolor** [comment]
just use the pig emoji ez

**Comment by humboldt123** [comment]
Anyone is free to submit and update a pr of this

**Comment by Microtransagolor** [comment]
pr?
