### ISSUE TITLE
meme command 

### ISSUE THREAD

**Issue by Microtransagolor** [humboldt123/the-thunderhead#43]
this could go with the fun catergory i suggested earlier, you upload an image and say /meme toptext bottomtext to use it

**Comment by humboldt123** [comment]
You have singlehandedly doubled the amount of issues here on the Github but I can do that as well

**Comment by Microtransagolor** [comment]
i thought you wanted suggestions, the bot needs work and i want to say why

**Comment by humboldt123** [comment]
I wanted suggestions, i was just memeing

**Comment by humboldt123** [comment]
This is actually super do-able with `canvas` so I can work on it tomorrow!
