### ISSUE TITLE
Ban reasons

### ISSUE THREAD

**Issue by Microtransagolor** [humboldt123/the-thunderhead#48]
make it so when you ban/kick/mute somebody thunderhead dms them a reason if you write one and you can make thunderhead dm people when their tempban is lifted maybe(also optional)

**Comment by humboldt123** [comment]
This is also an issue in another bot I'm working on so I'll write the same code for both.

**Comment by Microtransagolor** [comment]
another bot?

**Comment by humboldt123** [comment]
https://github.com/kami-blue/bot

**Comment by humboldt123** [comment]
https://github.com/kami-blue/bot/issues/4

**Comment by Microtransagolor** [comment]
interesting
